image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn package -B -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test -Dspring.profiles.active=test -Dtest='*Test'
