image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn package -B -DskipTests=true

test:
  stage: test
  script:
    - mvn test -Pci-tests -Dspring.profiles.active=test -Dtest='*Test'
