image: maven:latest

stages:
  - build
  - test
  - jacoco
  - owasp

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn package -B -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  services:
    - name: mysql:latest
      alias: test-db
  script:
    - mvn test -Dspring.profiles.active=test
  variables:
    MYSQL_DATABASE: test_db
    MYSQL_USER: testuser
    MYSQL_PASSWORD: testpassword
    MYSQL_ROOT_PASSWORD: rootpassword
    SPRING_DATASOURCE_URL: jdbc:mysql://test-db:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true
  coverage: '/Total\s*:\s*([\d\.]+)%/'

jacoco:
  stage: jacoco
  script:
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  artifacts:
    paths:
      - target/site/jacoco/

owasp:
  stage: owasp
  script:
    - mvn org.owasp:dependency-check-maven:check
  artifacts:
    paths:
      - target/dependency-check-report.html