image: maven:latest

stages:
  - build
  - test

before_script:
  - apt-get update
  - apt-get install -y docker-compose

build:
  stage: build
  script:
    - mvn package -B -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - docker-compose up -d test-db
    - mvn test
  services:
    - docker:dind
  variables:
    MYSQL_DATABASE: test_db
    MYSQL_USER: testuser
    MYSQL_PASSWORD: testpassword
    MYSQL_ROOT_PASSWORD: rootpassword