image: maven:3.8-jdk-11

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn package -B -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test